Repository ishaangupta-YB/Hacktoberfest-2022, pull requests merged in 2022-09, with the labels that each got.

#2 Create Profiles.md
  DigitalArtists/Profiles.md
Labels: good first issue, hacktoberfest-accepted

#4 flask
  Python/flask.py
Labels: good first issue, hacktoberfest-accepted

#6 Added Port Scanner Script in Python
  Python/port_scanner.py
  contributors/smit-sms.json
Labels: good first issue, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#10 Merge Changes
  DSA/BinarySearch.java
  contributors/Anonymous866.json
Labels: hacktoberfest-accepted

#11 Added binomial expansion series & username
  CP/binomial_expansion_series.py
  contributors/deepu13.json
Labels: good first issue, hacktoberfest-accepted

#13 added
  Python/reverse_string.py
  contributors/Danuragtiwari.json
Labels: good first issue, hacktoberfest-accepted

#15 Create its-puneet.json
  contributors/its-puneet.json
Labels: good first issue, hacktoberfest-accepted

#16 Create Adithh.json
  contributors/Adithh.json
Labels: good first issue, hacktoberfest-accepted

#12 Creating sudoku solver
  Algorithms/sudokusolver.py
Labels: good first issue, hacktoberfest-accepted

#17 added DSA with CPP codes
  DSA/C++/ArrayRotation.cpp
  DSA/C++/BinarySearch.cpp
  DSA/Java/ArrayRotation.java
  DSA/Java/BinarySearch.java
  contributors/amajaying.json
Labels: good first issue

#18 added github username
  contributors/Rishabhco.json
Labels: good first issue, hacktoberfest-accepted

#19 Toukir contribution
  contributors/toukirkhan.json
  open-CV/RectangleOnFaces.py
Labels: good first issue, hacktoberfest-accepted

#14 added program for counting negatives in a 2d matrix
  DSA/count_negatives_in_a_matrix.py
Labels: good first issue, hacktoberfest-accepted

#23 Added a CP problem and contribution json file
  CP/Mark_and_His_Unfinished_Essay.cpp
  contributors/Rockhopper130.json
Labels: good first issue, hacktoberfest-accepted

#22 Create anantpatel31.json
  contributors/anantpatel31.json
Labels: good first issue, hacktoberfest-accepted

#25 Create mayankdhnkr.json
  contributors/mayankdhnkr.json
Labels: good first issue, hacktoberfest-accepted

#26 Bhavik0902.json
  contributors/Bhavik0902.json
Labels: good first issue, hacktoberfest-accepted

#24 InsertionSort.cpp
  DSA/C++/InsertionSort.cpp
Labels: good first issue, hacktoberfest-accepted

#28 TravellingSalseman.cpp
  DSA/C++/TravellingSalseman.cpp
Labels: good first issue, hacktoberfest-accepted

#29 N_Qeen.cpp
  DSA/C++/N_Qeen.cpp
Labels: hacktoberfest-accepted

#30 Create dijkstra-algorithm.py
  Algorithms/dijkstra-algorithm.py
Labels: good first issue, hacktoberfest-accepted

#34 Create droid31.json
  contributors/droid31.json
Labels: good first issue, hacktoberfest-accepted

#33 Create longest_subarray.py
  Algorithms/longest_subarray.py
Labels: good first issue, hacktoberfest-accepted

#32 Create minimum_coin_change.py
  Algorithms/minimum_coin_change.py
Labels: hacktoberfest-accepted

#31 Create floyd_warshall.py
  Algorithms/floyd_warshall.py
  Algorithms/longest_common_subsequence.py
Labels: hacktoberfest-accepted

#21 Create convex-hull.py
  Algorithms/convex-hull.py
Labels: good first issue, hacktoberfest-accepted

#20 Armstrong.cpp
  DSA/C++/Armstrong.cpp
Labels: good first issue, hacktoberfest-accepted
