Repository ishaangupta-YB/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#36 Created Circular queue.java
  DSA/Java/Circular queue.java
Labels: good first issue, hacktoberfest-accepted

#38 Create Pranav.json
  contributors/Pranav.json
Labels: good first issue, hacktoberfest-accepted

#37 Create SimpleCNN.py
  Python/SimpleCNN.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#39 Create SendEmail.py
  Python/SendEmail.py
Labels: hacktoberfest-accepted

#41 Create Pickle.py
  Python/Pickle.py
Labels: hacktoberfest-accepted

#42 created amazing_design.py
  Python/amazing_design.py
Labels: good first issue, hacktoberfest-accepted

#43 created AdityaWadkar.json
  contributors/AdityaWadkar.json
Labels: good first issue, hacktoberfest-accepted

#45 Playing with OpenCV - Basics
  contributors/swapnilvishwakarma.json
  open-CV/ImageProcessing.py
  open-CV/man_portrait.jpeg
Labels: good first issue, hacktoberfest-accepted

#46 added youtube video downloader script in python + my name
  Python/Youtube-video-downloader.py
  contributors/srinjoy-26.json
Labels: good first issue, hacktoberfest-accepted

#48 Added GUI calculator in python
  Python/GUI_calculator.py
Labels: good first issue, hacktoberfest-accepted

#49 Hacktoberfest ML Project
  Machine Learning/Heart-Disease-Prediction/heart.ipynb
  Machine Learning/Heart-Disease-Prediction/heart_disease_data.csv
  Machine Learning/Heart-Disease-Prediction/random_test.csv
  contributors/souvik0306.json
Labels: good first issue, hacktoberfest-accepted

#51 Utkarsh Contribution Image Rotate Problem
  C++/rotateimage.cpp
  contributors/utkarsh.json
Labels: good first issue, hacktoberfest-accepted

#55 Create SimranSharma.json
  contributors/SimranSharma.json
Labels: good first issue, hacktoberfest-accepted

#54 Create Als1510.json
  contributors/Als1510.json
Labels: good first issue, hacktoberfest-accepted

#52 Tic-Tac-Toe in C language
  C/TicTacToeGame_Cfiles/README.md
  C/TicTacToeGame_Cfiles/tictactoe.c
Labels: good first issue, hacktoberfest-accepted, Add Your Name In Contributors Folder

#57 Add Bubble sort in Dsa java folder
  DSA/Java/BubbleSort.java
  contributors/vai-bhav-github.json
Labels: good first issue, hacktoberfest-accepted

#60 Queue_Data_Structure
  C++/Queue/1. Basic_Queue_Operation.c++
  C++/Queue/2. Implementation_Of_Queue.c++
  C++/Queue/3. Circular_Queue.c++
  C++/Queue/4. Doubly_Ended_Queue.c++
  C++/Queue/5.implementation_Of_Doubly_Ended_Queue.c++
  C++/Queue/6. Implementation_Of_Queue_using_Stack.c++
  contributors/Pawan.json
Labels: good first issue, hacktoberfest-accepted

#56 TIC TAC TOE Game
  C/game.cpp
Labels: good first issue, hacktoberfest-accepted

#68 Create Pragati_sawaliiya_json
  contributors/Pragati_sawaliiya_json
Labels: Hacktoberfest-Accepted

#66 Permutation of a number
  C++/permutaion_of_a_number.cpp
  CP/permutaion_of_a_number.cpp
Labels: good first issue, Hacktoberfest-Accepted

#69 Create median_of_2_sorted_array.py
  DSA/python/median_of_2_sorted_array.py
Labels: good first issue, Hacktoberfest-Accepted

#71 Create avyayjain.json
  contributors/avyayjain.json
Labels: good first issue, Hacktoberfest-Accepted

#70 Add armstrong number.java
  Java/Armstrong_Numbers.java
  contributors/imlakshay08.json
Labels: Star repo and Add Your Name In Contributors Folder

#78 Optimized Bubble Sort
  Java/BubbleSortOptimized.java
  contributors/PriyanshuJain.json
Labels: good first issue, Hacktoberfest-Accepted

#83 Create lognoroy.json
  contributors/lognoroy.json
Labels: Hacktoberfest-Accepted

#87 Create script.js
  Web Development/MYDAY-Js Project/js/script.js
Labels: Hacktoberfest-Accepted

#86 Create style.css
  Web Development/MYDAY-Js Project/css/style.css
Labels: Hacktoberfest-Accepted

#85 Create index.html
  Web Development/MYDAY-Js Project/index.html
Labels: Hacktoberfest-Accepted

#84 Create Description
  Web Development/MYDAY-Js Project/Description
Labels: Hacktoberfest-Accepted

#89 Added Backtracking problem solution
  C++/Backtracking_ReachTheTarget.cpp
  contributors/VedPrakashBhaskar.json
Labels: good first issue, Hacktoberfest-Accepted

#90 added to footer
  Web Development/HTML-Projects/Anaemia/aman.css
  Web Development/HTML-Projects/Anaemia/footer.css
  contributors/tylerb.json
Labels: good first issue, Hacktoberfest-Accepted, Star this repository to get featured

#88 Added Python Program to Find Square Root of a Number
  Python/squareRoot.py
  contributors/AhzamAkhtar.json
Labels: Hacktoberfest-Accepted

#94 added egg-dropping puzzel in c++
  C++/egg-droping-puzzel.cpp
  contributors/VishalSharma8910.json
Labels: good first issue, Hacktoberfest-Accepted

#96 Added Js project OTP Generator
  Web Development/JS-Projects/OTP-Generator/index.html
  Web Development/JS-Projects/OTP-Generator/script.js
  Web Development/JS-Projects/OTP-Generator/style.css
  contributors/MohamedIhsan.json
Labels: Hacktoberfest-Accepted

#98 Adds to do list project in Web Development folder
  Web Development/to-do-list/.gitignore
  Web Development/to-do-list/README.md
  Web Development/to-do-list/index.html
  Web Development/to-do-list/scripts/main.js
  Web Development/to-do-list/styles/style.css
  contributors/ayushknath.json
Labels: good first issue, Hacktoberfest-Accepted

#91 add equation of line finder and tkinter design
  Python/equationofline.py
  Python/tkintergraph.py
  contributors/jeffrey-zang.json
Labels: good first issue, Hacktoberfest-Accepted

#103 findGoodNodes.java
  Java/findGoodNodes.java
Labels: good first issue, Hacktoberfest-Accepted

#82 Create index.html
  Web Development/index.html
Labels: Hacktoberfest-Accepted

#81 Create Description
  Web Development/Description
Labels: Star repo and Add Your Name In Contributors Folder

#105 Create Dulyaaa.json
  contributors/Dulyaaa.json
Labels: Hacktoberfest-Accepted

#95 Add basics of image processing
  Image Processing/Basics/2.jpg
  Image Processing/Basics/3.jpg
  Image Processing/Basics/get-pip.py
  Image Processing/Basics/girl.png
  Image Processing/Basics/lab 1.ipynb
Labels: Hacktoberfest-Accepted

#104 DSA-binary search
  DSA/C++/search_in_rotated_sorted_array.cpp
Labels: good first issue, Hacktoberfest-Accepted

#109 Simple Website for Social Links
  Projects/SimpleSocialLinksWebsite/config.css
  Projects/SimpleSocialLinksWebsite/index.html
  Projects/SimpleSocialLinksWebsite/main.css
  Projects/SimpleSocialLinksWebsite/style.css
  contributors/ratchanondev.json
Labels: Hacktoberfest-Accepted

#99 Create Longest-Palindromic-Substring.py
  Longest-Palindromic-Substring.py
Labels: Star repo and Add Your Name In Contributors Folder

#97 Best Sum DP
  Javascript/bestSum.js
  contributors/mit.json
Labels: Hacktoberfest-Accepted

#114 Add bubble sort algorithm
  Python/burbuja1.py
  contributors/Josephglz.json
Labels: Hacktoberfest-Accepted

#139 hacktoberfest 2022
  Java/Banking-Application/BankingApplication.java
  Java/Banking-Application/README.md
Labels: Hacktoberfest-Accepted

#93 Linear Regression
  Machine Learning/Linear Regression.py
Labels: good first issue, Hacktoberfest-Accepted

#127 - add email validation for swift
  Swift/emailvalidation.swift
  contributors/balitax.json
Labels: good first issue, Hacktoberfest-Accepted

#124 added progress_bar.py
  Python/progress_bar.py
  contributors/ashwin.json
Labels: Hacktoberfest-Accepted

#110 Created a Binary Search Program Using C++
  C++/Binary Search.cpp
Labels: Hacktoberfest-Accepted

#121 Word break problem using dynamic programming
  DSA/C++/Word break problem using dynamic programming.cpp
Labels: Hacktoberfest-Accepted

#120 Minimum and Maximum values of given expression with + and *
  DSA/C++/Minimum and Maximum values of given expression with + and *.cpp
Labels: Hacktoberfest-Accepted

#111 Dijsktra Algorithm
  C++/Dijkstra’s shortest path algorithm.cpp
Labels: Hacktoberfest-Accepted

#143 Added some code snippet
  C++/Matrix_Multiplication.cpp
  DSA/C++/Bubble_Sort.cpp
  contributors/ChiragArora.json
Labels: good first issue, Hacktoberfest-Accepted

#119 Rat in a maze problem using backtracking
  DSA/C++/Rat in a maze problem using backtracking.cpp
Labels: Hacktoberfest-Accepted

#112 Opening and Closing Gate Problem
  DSA/C++/Opening and Closing Gate problem.cpp
Labels: Hacktoberfest-Accepted

#118 Subset Sum Problem
  DSA/C++/Subset Sum Problem.cpp
Labels: Hacktoberfest-Accepted

#117 Find minimum number of jumps to reach end of an array
  DSA/C++/Find minimum number of jumps to reach end of an array.cpp
Labels: Hacktoberfest-Accepted

#115 Create Count of all n digits numbers with digits in non-decreasing or…
  DSA/C++/Count of all n digits numbers with digits in non-decreasing order.cpp
Labels: Hacktoberfest-Accepted

#116 Create Maximum number of A's using four keys.cpp
  DSA/C++/Maximum number of A's using four keys.cpp
Labels: Hacktoberfest-Accepted

#113 Finding total Number of islands
  DSA/C++/Find the Total Number of Islands.cpp
Labels: Hacktoberfest-Accepted

#142 Create quiz-game.py
  Python/quiz-game.py
  contributors/ajay007e.json
Labels: Hacktoberfest-Accepted

#132 Added python code for various tree traversals
  Python/Tree_traversal_inorder.py
  Python/Tree_traversal_postorder.py
  Python/Tree_traversal_preorder.py
  contributors/adityap301.json
Labels: Hacktoberfest-Accepted

#148 change capital -V to simple -v in readme file
  README.md
  contributors/MasterBrian99.json
Labels: documentation

#129 Create Merge_sort.cpp
  DSA/C++/Merge_sort.cpp
Labels: good first issue, Hacktoberfest-Accepted

#149 Xml to Csv converter script
  Python/xml_to_csv.py
  contributors/Preetam2114.json
Labels: good first issue, Hacktoberfest-Accepted

#146 Abhishek
  C++/combination.cpp
  contributors/Sultaniya.json
Labels: Hacktoberfest-Accepted

#131 Create Binary_search.cpp
  C++/Binary_search.cpp
Labels: Hacktoberfest-Accepted

#134 Update reverse_string.py
  Python/reverse_string.py
Labels: Star repo and Add Your Name In Contributors Folder

#125 Gets the state county and state column for each long coordinate in Geopy
  Python/GetLocation.py
Labels: Star repo and Add Your Name In Contributors Folder

#126 alarm clock sederhana dengan tampilan GUI yang didesain menggunakan OOP
  Python/Alarm-Clock.py
Labels: Hacktoberfest-Accepted

#153 Add javascript and contributor
  Javascript/sort.js
  contributors/Yingchid.json
Labels: good first issue, Hacktoberfest-Accepted

#156 add tower of hanoi algorithm in algorithms folder
  Algorithms/tower-of-hanoi-algorithm.go
  contributors/DevanoFahrurossi.json
Labels: good first issue, Hacktoberfest-Accepted

#159 Added shinchan.py and updated contributors folder
  Python/shinchan.py
  contributors/ashishshukla09.json
Labels: good first issue, Hacktoberfest-Accepted

#141 Create clock-app.js
  Javascript/clock-app.js
Labels: Star repo and Add Your Name In Contributors Folder

#102 Added questions of medium level
  C++/Multiply_Strings.cpp
  C++/Reverse_integer.cpp
Labels: Star repo and Add Your Name In Contributors Folder

#157 Create number_guesser.py
  Python/number_guesser.py
Labels: Hacktoberfest-Accepted, Star repo and Add Your Name In Contributors Folder

#154 Create snake-water-gun.py
  Python/snake-water-gun.py
Labels: Star repo and Add Your Name In Contributors Folder

#160 Linked list
  .gitignore
  C/linked-list/Makefile
  C/linked-list/src/linked_list.c
  C/linked-list/src/linked_list.h
  C/linked-list/src/main.c
  contributors/Lohan-Yrvine.json
Labels: Hacktoberfest-Accepted

#161 Created hill_cipher.py
  Python/hill_cipher.py
  contributors/Nidhay.json
Labels: Hacktoberfest-Accepted

#166 Added python tictactoe game
  Python/TicTacToe_GUI.py
  contributors/RoyalBosS-Ayush.json
Labels: Hacktoberfest-Accepted

#163 Added Python script and added to contributions
  DSA/python/get_all_substrings.py
  contributors/jordanhilado.json
Labels: Hacktoberfest-Accepted

#1 Added a snippet
  Python/sortalistofdictionaries.py
Labels: good first issue, Star repo and Add Your Name In Contributors Folder

#169 Reversing a Linked List
  C++/Reversing_Linked_List.cpp
  contributors/BabyElias.json
Labels: Star repo and Add Your Name In Contributors Folder

#181 Create Butterfly_Pattern.cpp
  C++/Butterfly_Pattern.cpp
Labels: Hacktoberfest-Accepted

#175 adding Palindrome_string
  Python/Palindrome_string.py
  contributors/bagusyumna.json
Labels: Star repo and Add Your Name In Contributors Folder

#177 Added Quiz using Python
  Quiz.py
Labels: Hacktoberfest-Accepted

#191 Function to determine whether agument is a square number
  Javascript/isSquare.js
  contributors/harrycs1.json
Labels: Hacktoberfest-Accepted

#192 C program + Contributors.md updated
  C/Character is alphabet checker.c
  contributors/Muhammad Noorani.json
Labels: Hacktoberfest-Accepted

#178 Create Video_player.py
  Video_player.py
Labels: Star repo and Add Your Name In Contributors Folder

#197 Added transpose of a sparse matrix program.
  C/transpose-sparse.c
Labels: Star repo and Add Your Name In Contributors Folder

#201 added date between two dates function
  Python/date_between_two_dates.py
  contributors/LMC23.json
Labels: Star repo and Add Your Name In Contributors Folder

#136 Added a Brain Stroke Prediction Model
  Machine Learning/Brain-Stroke-Prediction/BrainStrokePrediction.ipynb
  Machine Learning/Brain-Stroke-Prediction/stroke-data.csv
Labels: Star repo and Add Your Name In Contributors Folder

#202 created c++ program to swap alternate elements
  C++/SwapAlternateElements.cpp
  C++/SwapAlternateElements.exe
  contributors/sudhanshu.json
Labels: Star repo and Add Your Name In Contributors Folder

#207 Create Subarray_Sum_Equals_K.py
  Python/Subarray_Sum_Equals_K.py
Labels: Hacktoberfest-Accepted

#229 Added a tetris game in the Game Development Folder
  Game Development/TetrisGame/TetrisBasic.js
  Game Development/TetrisGame/index.html
  Game Development/TetrisGame/mainstyle.css
  Game Development/TetrisGame/text
  contributors/VinodKuril.json
Labels: good first issue, Hacktoberfest-Accepted

#223 Added audio extractor from video
  Python/Audio_extractor.py
Labels: good first issue, Hacktoberfest-Accepted, Star repo and Add Your Name In Contributors Folder

#238 Added TicTacToe game for the Terminal
  Python/TicTacToe_Terminal.py
  contributors/ChadCodee.json
Labels: Star repo and Add Your Name In Contributors Folder

#226 Drum-Kit-Game
  P-2 Drum Kit game/images/crash.png
  P-2 Drum Kit game/images/kick.png
  P-2 Drum Kit game/images/snare.png
  P-2 Drum Kit game/images/tom1.png
  P-2 Drum Kit game/images/tom2.png
  P-2 Drum Kit game/images/tom3.png
  P-2 Drum Kit game/images/tom4.png
  P-2 Drum Kit game/index.html
  P-2 Drum Kit game/index.js
  P-2 Drum Kit game/sounds/crash.mp3
  P-2 Drum Kit game/sounds/kick-bass.mp3
  P-2 Drum Kit game/sounds/snare.mp3
  P-2 Drum Kit game/sounds/tom-1.mp3
  P-2 Drum Kit game/sounds/tom-2.mp3
  P-2 Drum Kit game/sounds/tom-3.mp3
  P-2 Drum Kit game/sounds/tom-4.mp3
  P-2 Drum Kit game/styles.css
Labels: Star repo and Add Your Name In Contributors Folder

#260 Added Important codes in java using recursion and Quiz App
  DSA/Java/GCD.java
  DSA/Java/PowerOfNumber.java
  Java/BinarySearchUsingRecursion.java
  Javascript/index.html
  Javascript/script.js
  Javascript/style.css
  contributors/Aarize29.json
Labels: Star repo and Add Your Name In Contributors Folder

#258 New Java Program added
  Java/IsPrime.java
  contributors/ramakrishna-mrk.json
Labels: Star this repository to get featured

#266 Added packetsniffer code - C will be much better in C++
  C/packetsniffer/main.c
  C/packetsniffer/sniffer.exe
Labels: Star repo and Add Your Name In Contributors Folder

#264 Notes making website build through Javascript
  Projects/NoteMakingWebsite/index.html
  Projects/NoteMakingWebsite/myNotes.js
  Projects/NoteMakingWebsite/readme.md
Labels: Star repo and Add Your Name In Contributors Folder

#265 Notepad using python
  Python/Notepad/Images/Simple_notepad.png
  Python/Notepad/Notepad.py
Labels: Star repo and Add Your Name In Contributors Folder

#251 Added Patterns.py and added name in contributors
  Python/Patterns.py
  contributors/Kunalp02.json
Labels: Star this repository to get featured

#252 Added basic Linked List programs.
  Java/Linked_Lists/Doubly_Linked_List.java
  Java/Linked_Lists/Singly_Linked_List.java
  contributors/divyansh-ag-03.json
Labels: Star this repository to get featured

#164 Create CVSS.js
  Javascript/CVSS.js
Labels: good first issue

#225 Android fingerprint.java
  App Development/AndroidFingerprint.java
Labels: good first issue
